language: generic
os: osx

env:
  - PYVER=3.6.4
  - PYVER=2.7.14
  - PYVER=pypy2.7-5.8.0
  - PYVER=pypy3.5-5.8.0

before_install:
  - brew update
  - brew upgrade pyenv
  - which pyenv
  - pyenv --version
  - eval "$(pyenv init -)"
  - pyenv versions
  - pyenv install -l
  - pyenv install $PYVER
  - pyenv global $PYVER
  - pyenv versions
  - which python
  - python --version
  - which pip
  - pip --version

install:
  - pip install netCDF4

script:
  - ./main.py
