language: generic
os: osx

env:
  - PYVER=3.6.4
  - PYVER=2.7.14

before_install:
#  - brew --version
#  - brew update
#  - brew install pyenv
#  - eval "$(pyenv init -)"
  - pyenv install -l
  - pyenv install $PYVER
  - pyenv global $PYVER

install:
  - pip install netCDF4

script:
  - which python
  - which pip
  - python --version
  - pip --version
  - ./main.py
