language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode9.3beta
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4

env:
  - PYVER=3.6.4
  - PYVER=2.7.14

before_install:
#  - brew --version
#  - brew update
#  - brew install pyenv
#  - eval "$(pyenv init -)"
  - pyenv install -l
  - pyenv install $PYVER
  - pyenv global $PYVER

install:
  - pip install netCDF4

script:
  - which python
  - which pip
  - python --version
  - pip --version
  - ./main.py
